[build]
publish = "exampleSite/public"
command = "rm -f -r exampleSite/public && hugo -v --source=exampleSite --themesDir ../ --gc"

[build.environment]
HUGO_VERSION = "0.88.1"
HUGO_THEME = "repo"
HUGO_BASEURL = "https://ublogger.netlify.app"

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"